window.techData = {
    products: [
        // --- MOBILE HARDWARE (Phones) ---
        {
            id: 1160,
            name: "Lava Yuva 4 Pro",
            category: "Phone",
            price: "₹8,999",
            priceValue: 8999,
            specs: { display: "6.5\" 90Hz LCD", cpu: "Unisoc T616", ram: "6GB", storage: "128GB" },
            image: "assets/final assets/lava strom1.jpg",
            images: ["assets/final assets/lava strom1.jpg"],
            pros: ["Glass Back Design", "Clean Android 14", "90Hz Smooth Display"],
            cons: ["Slow Charging", "Single Speaker", "Basic Low Light"],
            description: "An elegant budget contender from India, offering a premium glass back and a clean software experience.",
            antutu: 320000,
            cameraRating: 5.5,
            segment: "ALL_ROUNDER",
            releaseDate: "January 2026",
            link: "https://www.amazon.in/s?k=Lava+Yuva+4+Pro"
        },


        {
            id: 1163,
            name: "Realme C75",
            category: "Phone",
            price: "₹9,499",
            priceValue: 9499,
            specs: { display: "6.72\" 90Hz LCD", cpu: "Helio G91", ram: "6GB", storage: "128GB" },
            image: "assets/products/n2.jpg",
            images: ["assets/products/n2.jpg"],
            pros: ["Stylish Sunburst Design", "Good Main Camera (50MP)", "Loud Speaker Output"],
            cons: ["No 5G Support", "Average Performance", "Slow Charging"],
            description: "A lifestyle budget phone focusing on camera aesthetics and a flashy design language.",
            antutu: 280000,
            cameraRating: 5.5,
            segment: "ALL_ROUNDER",
            releaseDate: "January 2026",
            link: "https://www.amazon.in/s?k=Realme+C75"
        },
        {
            id: 1164,
            name: "Poco C75",
            category: "Phone",
            price: "₹8,499",
            priceValue: 8499,
            specs: { display: "6.88\" 120Hz LCD", cpu: "Helio G81-Ultra", ram: "6GB", storage: "128GB" },
            image: "assets/products/115.jpg",
            images: ["assets/products/115.jpg"],
            pros: ["Massive Media Display", "120Hz Smoothness on Budget", "Unique Textured Back"],
            cons: ["Relatively Heavy", "Average Battery Efficiency", "Lower density pixels"],
            description: "The biggest screen in the sub-10k segment, perfect for video streaming and browsing.",
            antutu: 260000,
            cameraRating: 5.2,
            segment: "ALL_ROUNDER",
            releaseDate: "December 2025",
            link: "https://www.amazon.in/s?k=Poco+C75"
        },

        {
            id: 1166,
            name: "Vivo Y19s",
            category: "Phone",
            price: "₹9,299",
            priceValue: 9299,
            specs: { display: "6.68\" 90Hz LCD", cpu: "Unisoc T612", ram: "4GB", storage: "128GB" },
            image: "assets/products/202.jpg",
            images: ["assets/products/202.jpg"],
            pros: ["Thin and Light Design", "IP54 Rating", "Good Build Quality"],
            cons: ["Lower Performance", "Slow Charging", "Average UI speed"],
            description: "A stylish budget offering from Vivo, focusing on durability and a slim hand-feel.",
            antutu: 2550000,
            cameraRating: 5.3,
            segment: "ALL_ROUNDER",
            releaseDate: "January 2026",
            link: "https://www.amazon.in/s?k=Vivo+Y19s"
        },
        {
            id: 1167,
            name: "Infinix Smart 9 Plus",
            category: "Phone",
            price: "₹7,999",
            priceValue: 7999,
            specs: { display: "6.6\" 120Hz LCD", cpu: "Helio G36", ram: "4GB", storage: "64GB" },
            image: "assets/products/n2.jpg",
            images: ["assets/products/n2.jpg"],
            pros: ["120Hz Refresh on Entry", "Magic Ring Interaction", "Great Price"],
            cons: ["Basic Processor", "HD+ Resolution", "Plastic Build"],
            description: "Bringing high refresh rates to the most affordable segment for a smooth modern feel.",
            antutu: 180000,
            cameraRating: 4.8,
            segment: "ALL_ROUNDER",
            releaseDate: "December 2025",
            link: "https://www.amazon.in/s?k=Infinix+Smart+9"
        },
        {
            id: 1168,
            name: "Itel P65",
            category: "Phone",
            price: "₹8,999",
            priceValue: 8999,
            specs: { display: "6.7\" 120Hz LCD", cpu: "Unisoc T615", ram: "8GB", storage: "128GB" },
            image: "assets/products/n3.jpg",
            images: ["assets/products/n3.jpg"],
            pros: ["Aggressive Cyber Design", "Charging Case Included", "High RAM for price"],
            cons: ["Brand perceived low", "UI is cluttered", "Basic camera"],
            description: "A unique futuristically styled phone that comes with its own charging case in the box.",
            antutu: 290000,
            cameraRating: 4.9,
            segment: "ALL_ROUNDER",
            releaseDate: "November 2025",
            link: "https://www.amazon.in/s?k=Itel+P65"
        },

        {
            id: 1001,
            name: "Samsung Galaxy S26 Ultra",
            category: "Phone",
            price: "₹1,34,999",
            priceValue: 134999,
            specs: { display: "6.9\" Dynamic AMOLED 3X", cpu: "Snapdragon 8 Gen 5", ram: "16GB", storage: "512GB" },
            image: "assets/products/111.jpg",
            images: ["assets/products/111.jpg", "assets/samsung-galaxy-s24-ultra-5g-sm-s928-4.jpg"],
            pros: ["Advanced AI 2.0 Integration", "New Slim Titanium Frame", "200MP Gen 3 Sensory System"],
            cons: ["Very Large Footprint", "Premium Enthusiast Pricing", "No Charging Brick in Box"],
            description: "The 2026 flagship from Samsung, redefining mobile intelligence and professional photography with the Snapdragon 8 Gen 5 and a refined Titanium build.",
            antutu: 2450000,
            cameraRating: 9.8,
            segment: "PRO",
            releaseDate: "January 2026",
            link: "https://www.amazon.in/s?k=Galaxy+S26+Ultra"
        },
        {
            id: 1002,
            name: "iPhone 17 Pro Max",
            category: "Phone",
            price: "₹1,64,900",
            priceValue: 164900,
            specs: { display: "6.9\" ProMotion OLED", cpu: "A19 Pro", ram: "12GB", storage: "256GB" },
            image: "assets/products/402.jpg",
            images: ["assets/products/402.jpg", "assets/products/401.jpg"],
            pros: ["A19 Pro Silicon Efficiency", "Under-display FaceID Technology", "Unified 48MP Triple Stack"],
            cons: ["Highest Market Entry Price", "Charging Speed remains at 25W", "Considerable Weight"],
            description: "Apple's 2025 pinnacle device, featuring the massive A19 Pro chip and a significantly refined Always-On display.",
            antutu: 2350000,
            cameraRating: 9.7,
            segment: "PRO",
            releaseDate: "September 2025",
            link: "https://www.amazon.in/s?k=iPhone+17+Pro+Max"
        },
        {
            id: 1003,
            name: "Google Pixel 10 Pro",
            category: "Phone",
            category_ind: "Phone",
            price: "₹1,19,999",
            priceValue: 119999,
            specs: { display: "6.7\" LTPO OLED", cpu: "Tensor G5 (TSMC)", ram: "16GB", storage: "256GB" },
            image: "assets/google-pixel-9-pro.jpg",
            images: ["assets/google-pixel-9-pro.jpg", "assets/google-pixel-9-pro-1.jpg"],
            pros: ["First TSMC-manufactured Tensor", "Unmatched Computational Photography", "Generative AI OS Integration"],
            cons: ["Limited Service Center Coverage", "Slower Wired Charging", "Industrial Camera Bar Design"],
            description: "The long-awaited TSMC Tensor G5 makes the Pixel 10 Pro a performance beast alongside Google's legendary AI-driven camera software.",
            antutu: 1950000,
            cameraRating: 9.9,
            segment: "CAMERA",
            releaseDate: "October 2025",
            link: "https://www.flipkart.com/google-pixel-10-pro-store"
        },
        {
            id: 1004,
            name: "OnePlus 14",
            category: "Phone",
            price: "₹74,999",
            priceValue: 74999,
            specs: { display: "6.8\" 2K 144Hz OLED", cpu: "Snapdragon 8 Gen 5", ram: "16GB", storage: "512GB" },
            image: "assets/products/118.jpg",
            images: ["assets/products/118.jpg", "assets/products/203.jpg"],
            pros: ["Ultra-Fast 150W Charging", "Hasselblad Natural Color 3.0", "Exceptional Value Proposition"],
            cons: ["Alert Slider is Niche", "Telephoto lacks 10x Optical", "Aggressive Screen Curves"],
            description: "Fast and Smooth reaches its peak with the OnePlus 14, featuring industry-leading charging and a massive 2K AMOLED panel.",
            antutu: 2400000,
            cameraRating: 8.5,
            segment: "PERFORMANCE",
            releaseDate: "January 2026",
            link: "https://www.amazon.in/s?k=OnePlus+14"
        },
        {
            id: 1005,
            name: "Nothing Phone (3)",
            category: "Phone",
            price: "₹49,999",
            priceValue: 49999,
            specs: { display: "6.7\" 120Hz LTPO", cpu: "Snapdragon 8s Gen 4", ram: "12GB", storage: "256GB" },
            image: "assets/products/110.jpg",
            images: ["assets/products/110.jpg", "assets/products/n3.jpg"],
            pros: ["Evolved Glyph Interface", "Pure Android Experience", "Perfectly Symmetric Bezels"],
            cons: ["Distinct Aesthetic Niche", "No Power Adapter Included", "Camera is Great, Not Elite"],
            description: "Nothing returns with a more powerful internals and a refined Glyph design, aiming for a consistent high-performance experience.",
            antutu: 1550000,
            cameraRating: 8.0,
            segment: "ALL_ROUNDER",
            releaseDate: "July 2025",
            link: "https://www.amazon.in/s?k=Nothing+Phone+3"
        },


        {
            id: 1008,
            name: "Vivo X200 Pro",
            category: "Phone",
            price: "₹94,999",
            priceValue: 94999,
            specs: { display: "6.78\" 1.5K 144Hz", cpu: "Dimensity 9400", ram: "16GB", storage: "512GB" },
            image: "assets/products/151.jpg",
            images: ["assets/products/151.jpg", "assets/products/202.jpg"],
            pros: ["World-Leading Periscope Zoom", "Zeiss T* Anti-Reflective Coating", "Dedicated V3+ Imaging Silicon"],
            cons: ["Noticeable Price Increase", "Aggressive Curved Edges", "Software Updates Frequency"],
            description: "The ultimate portrait and landscape specialist with Zeiss professional optics and a high-performance MediaTek chipset.",
            antutu: 2250000,
            cameraRating: 9.8,
            segment: "CAMERA",
            releaseDate: "October 2025",
            link: "https://www.amazon.in/s?k=Vivo+X200+Pro"
        },
        {
            id: 1021,
            name: "Poco F7 Pro",
            category: "Phone",
            price: "₹34,999",
            priceValue: 34999,
            specs: { display: "6.67\" 1.5K 120Hz", cpu: "Snapdragon 8 Gen 4", ram: "12GB", storage: "256GB" },
            image: "assets/products/115.jpg",
            images: ["assets/products/115.jpg", "assets/products/n1.jpg"],
            pros: ["Elite Price-to-Performance", "Sharp 1.5K Resolution", "Aggressive Design Language"],
            cons: ["Plastic Frame Build", "MiUI System Ads", "Cameras are Functional Not Elite"],
            description: "The performance king return, offering flagship Snapdragon silicone at a mid-range price bracket.",
            antutu: 2000000,
            cameraRating: 7.0,
            segment: "PERFORMANCE",
            releaseDate: "May 2025",
            link: "https://www.amazon.in/s?k=Poco+F7+Pro"
        },
        {
            id: 1022,
            name: "Redmi Note 15 Pro+",
            category: "Phone",
            price: "₹31,999",
            priceValue: 31999,
            specs: { display: "6.7\" 1.5K Curved AMOLED", cpu: "Dimensity 8400", ram: "12GB", storage: "256GB" },
            image: "assets/products/n1.jpg",
            images: ["assets/products/n1.jpg", "assets/products/n2.jpg"],
            pros: ["IP69 Water Resistance", "Ultra-Slim Curved Design", "High Resolution Primary Sensor"],
            cons: ["Busy HyperOS Software", "Average Secondary Cameras", "Processor Lacks Peak Gaming Ops"],
            description: "Xiaomi's refined best-seller for 2026, combining style with rugged durability and solid specs.",
            antutu: 1300000,
            cameraRating: 8.0,
            segment: "ALL_ROUNDER",
            releaseDate: "January 2026",
            link: "https://www.amazon.in/s?k=Redmi+Note+15+Pro+Plus"
        },

        {
            id: 1029,
            name: "Samsung Galaxy F57",
            category: "Phone",
            price: "₹22,999",
            priceValue: 22999,
            specs: { display: "6.6\" 120Hz sAMOLED", cpu: "Exynos 1480", ram: "8GB", storage: "256GB" },
            image: "assets/products/120.jpg",
            images: ["assets/products/120.jpg", "assets/products/101.jpg"],
            pros: ["Exceptional Battery Life", "Trustworthy Samsung One UI", "Great AMOLED Quality"],
            cons: ["Thick External Bezels", "Slowest Charging in Segment", "Heavy Single-Hand Usage"],
            description: "Samsung's battery specialist for 2025, offering a simplified and reliable Android experience.",
            antutu: 750000,
            cameraRating: 7.5,
            segment: "Battery-Focused",
            releaseDate: "November 2025",
            link: "https://www.amazon.in/s?k=Samsung+Galaxy+F57"
        },
        {
            id: 1027,
            name: "Moto G86 5G",
            category: "Phone",
            price: "₹18,999",
            priceValue: 18999,
            specs: { display: "6.5\" 120Hz pOLED", cpu: "Snapdragon 6 Gen 3", ram: "8GB", storage: "128GB" },
            image: "assets/products/n3.jpg",
            images: ["assets/products/n3.jpg", "assets/products/n2.jpg"],
            pros: ["Clean Ad-Free Experience", "Pantone Standard Colors", "Loud Dual Stereo Speakers"],
            cons: ["Single Rear Main Camera", "Lower Antutu Score", "Average Low-Light Performance"],
            description: "Motorola's clean software champion for the budget 5G segment, focusing on usability and design.",
            antutu: 650000,
            cameraRating: 6.5,
            segment: "ALL_ROUNDER",
            releaseDate: "September 2025",
            link: "https://www.amazon.in/s?k=Moto+G86+5G"
        },



        // --- COMPUTING SYSTEMS (Laptops) ---
        {
            id: 1013,
            name: "MacBook Pro 16 (M5 Max)",
            category: "Laptop",
            price: "₹3,49,900",
            priceValue: 349900,
            specs: { display: "16.2\" 2000nit Mini-LED", cpu: "Apple M5 Max", ram: "64GB", storage: "1TB" },
            image: "assets/apple-m3-max-mrx83hn-a-159598-v1-original-1.avif",
            images: ["assets/apple-m3-max-mrx83hn-a-159598-v1-original-1.avif", "assets/products/502.jpg"],
            pros: ["Desktop-Grade 2nm Silicon", "24-Hour Real-World Use", "Liquid Retina XDR Clarity"],
            cons: ["Extremely High Investment", "Substantial Weight", "No Integrated Cellular option"],
            description: "Apple's 2026 workstation behemoth, designed for high-end rendering and AI model processing.",
            gpuRating: 10.0,
            antutu: 2800000,
            segment: "CREATOR_LAPTOP",
            releaseDate: "November 2025",
            link: "https://www.amazon.in/s?k=MacBook+Pro+M5+Max"
        },
        {
            id: 1101,
            name: "Dell G16 7650",
            category: "Laptop",
            price: "₹1,24,990",
            priceValue: 124990,
            specs: { display: "16\" 240Hz QHD+", cpu: "i7-15700HX", ram: "16GB", storage: "1TB" },
            image: "assets/msi thin15 gf63.jpg",
            images: ["assets/msi thin15 gf63.jpg", "assets/hp laptop 15.jpg"],
            pros: ["Mechanical Keyboard Switch Option", "High TGP Graphics Power", "Robust Alienware-inspired Cooling"],
            cons: ["Very Bulky Design", "Loud Cooling Fans", "Proprietary Large Charger"],
            description: "A performance-first gaming laptop that brings desktop-grade cooling to a semi-portable frame.",
            gpuRating: 8.5,
            antutu: 1250000,
            segment: "COMING_SOON",
            releaseDate: "March 2026",
            link: "https://www.amazon.in/s?k=Dell+G16+Laptop"
        },
        {
            id: 1039,
            name: "Lenovo ThinkPad X1 2026",
            category: "Laptop",
            price: "₹1,99,990",
            priceValue: 199990,
            specs: { display: "14\" 3K OLED", cpu: "Snapdragon X Elite 2", ram: "32GB", storage: "1TB" },
            image: "assets/products/323.jpg",
            images: ["assets/products/323.jpg", "assets/products/305.jpg"],
            pros: ["World-Class Keyboard Detail", "Passive Cooling Quietness", "Legendary Durability"],
            cons: ["ARM-based Compatibility Quirks", "Premium Corporate Pricing", "Limited Port Selection"],
            description: "The executive standard, now powered by the ultra-efficient Snapdragon X Elite 2 for multi-day usage.",
            gpuRating: 6.5,
            antutu: 1350000,
            segment: "COMING_SOON",
            releaseDate: "February 2026",
            link: "https://www.amazon.in/s?k=ThinkPad+X1+Carbon"
        },
        {
            id: 1037,
            name: "MacBook Air M4 (15\")",
            category: "Laptop",
            price: "₹1,34,900",
            priceValue: 134900,
            specs: { display: "15.3\" Liquid Retina", cpu: "Apple M4", ram: "16GB", storage: "256GB" },
            image: "assets/apple-m3-mxcu3hn-a-165756-v1-original-1.avif",
            images: ["assets/apple-m3-mxcu3hn-a-165756-v1-original-1.avif"],
            pros: ["Incredible Thinness", "Zero Noise (Fanless)", "Vibrant Large Canvas"],
            cons: ["Limited Ports (USBC)", "Slow Base SSD", "Pricey Upgrades"],
            description: "The fan-favorite thin-and-light gets a larger screen and the breakthrough M4 neural engine.",
            gpuRating: 7.5,
            antutu: 1550000,
            segment: "STUDENT_LAPTOP",
            releaseDate: "March 2025",
            link: "https://www.amazon.in/s?k=MacBook+Air+M4"
        },

        // --- TABLETS (India) ---
        {
            id: 1105,
            name: "iPad Mini 7",
            category: "Tablet",
            price: "₹49,900",
            priceValue: 49900,
            specs: { display: "8.3\" Liquid Retina", cpu: "Apple A18 Pro", ram: "8GB", storage: "128GB" },
            image: "assets/products/101.jpg",
            images: ["assets/products/101.jpg"],
            pros: ["Unmatched Compact Performance", "Apple Intelligence Support", "USB-C Versatility"],
            cons: ["No 120Hz ProMotion", "Relatively Small Target Audience", "High Accessories Entry"],
            description: "The ultimate power-tablet for the palm of your hand, now with Pro-series silicon.",
            antutu: 1650000,
            cameraRating: 7.5,
            segment: "ALL_ROUNDER",
            releaseDate: "October 2025",
            link: "https://www.amazon.in/s?k=iPad+Mini+7"
        },
        {
            id: 1106,
            name: "Samsung Galaxy Tab S11 FE",
            category: "Tablet",
            price: "₹39,999",
            priceValue: 39999,
            specs: { display: "10.9\" 90Hz LCD", cpu: "Exynos 1580", ram: "8GB", storage: "128GB" },
            image: "assets/products/111.jpg",
            images: ["assets/products/111.jpg"],
            pros: ["Free S-Pen in Box", "IP68 Water Resistance", "Samsung DeX Productivity"],
            cons: ["Display is LCD Not OLED", "Slow Charging Profile", "Bezels are Noticeable"],
            description: "A productivity-focused tablet for students and creators who need pen input and durability.",
            antutu: 950000,
            cameraRating: 7.0,
            segment: "COMING_SOON",
            releaseDate: "July 2026",
            link: "https://www.amazon.in/s?k=Galaxy+Tab+S11+FE"
        },
        // --- ADDING BATCH 3: FOLDABLES, GAMING & BUDGET ---
        {
            id: 1121,
            name: "OnePlus Open 2",
            category: "Foldable",
            price: "₹1,49,999",
            priceValue: 149999,
            specs: { display: "7.8\" Foldable LTPO", cpu: "Snapdragon 8 Gen 5", ram: "16GB", storage: "512GB" },
            image: "assets/products/403.jpg",
            images: ["assets/products/403.jpg"],
            pros: ["Thinest Global Foldable", "Hasselblad Camera System", "No-Gap Design"],
            cons: ["Higher Price Point", "Limited Retail Availability", "Heavy in pocket"],
            description: "The successor to the most successful foldable, now thinner, lighter, and faster with Hasselblad optics.",
            antutu: 2350000,
            cameraRating: 9.3,
            segment: "PRO",
            releaseDate: "December 2025",
            link: "https://www.amazon.in/s?k=OnePlus+Open+2"
        },


        {
            id: 1124,
            name: "Realme 14 Pro+ 5G",
            category: "Phone",
            price: "₹29,999",
            priceValue: 29999,
            specs: { display: "6.7\" 1.5K Curved", cpu: "Snapdragon 7s Gen 4", ram: "12GB", storage: "256GB" },
            image: "assets/products/116.jpg",
            images: ["assets/products/116.jpg"],
            pros: ["Stunning Luxury Design", "64MP Periscope Zoom", "Great Battery Stats"],
            cons: ["SoC is mid-range", "System Ads (Software)", "Charging speed is good but not best"],
            description: "The beauty champion of the mid-range, focusing on design aesthetics and periscope zoom capabilities.",
            antutu: 890000,
            cameraRating: 8.5,
            segment: "CAMERA",
            releaseDate: "July 2025",
            link: "https://www.amazon.in/s?k=Realme+14+Pro+Plus"
        },
        {
            id: 1125,
            name: "Vivo V50 Pro",
            category: "Phone",
            price: "₹46,999",
            priceValue: 46999,
            specs: { display: "6.78\" 120Hz AMOLED", cpu: "Snapdragon 7 Gen 5", ram: "12GB", storage: "512GB" },
            image: "assets/products/202.jpg",
            images: ["assets/products/202.jpg"],
            pros: ["Ultra-Slim Build", "Zeiss Professional Portraits", "Smart Aura Light System"],
            cons: ["Premium price for mid-range chip", "Curved screen fragility", "Bloatware apps"],
            description: "A lifestyle flagship focused on studio-quality portraits and a slim, elegant hand-feel.",
            antutu: 1150000,
            cameraRating: 9.0,
            segment: "CAMERA",
            releaseDate: "August 2025",
            link: "https://www.amazon.in/s?k=Vivo+V50+Pro"
        },





        {
            id: 1131,
            name: "Asus Zephyrus G14 (2026)",
            category: "Laptop",
            price: "₹1,69,990",
            priceValue: 169990,
            specs: { display: "14\" OLED 120Hz", cpu: "Ryzen 9 9900HS", ram: "32GB", storage: "1TB" },
            image: "assets/products/314.jpg",
            images: ["assets/products/314.jpg"],
            pros: ["World's Best 14-inch Gaming", "OLED Color Accuracy", "Portable Powerhouse"],
            cons: ["Solid RAM (Not upgradeable)", "Gets hot under heavy load", "Expensive"],
            description: "The ultimate 14-inch laptop for gamers and creators, now with a stunning OLED panel and Ryzen 9 power.",
            gpuRating: 9.2,
            antutu: 1650000,
            segment: "COMING_SOON",
            releaseDate: "June 2026",
            link: "https://www.amazon.in/s?k=Asus+Zephyrus+G14+2026"
        },
        {
            id: 1132,
            name: "HP Spectre x360 14 (2026)",
            category: "Laptop",
            price: "₹1,49,990",
            priceValue: 149990,
            specs: { display: "14\" 3K OLED Touch", cpu: "Core Ultra 7 Gen 2", ram: "16GB", storage: "1TB" },
            image: "assets/hp laptop 15.jpg",
            images: ["assets/hp laptop 15.jpg"],
            pros: ["Transformative 2-in-1 Design", "Elite Trackpad Experience", "Haptic Touchpad"],
            cons: ["Expensive for the specs", "Stylus cost extra", "Ports are limited"],
            description: "A luxury 2-in-1 notebook with industrial design and a breathtaking 3K OLED touch display.",
            gpuRating: 6.8,
            antutu: 1200000,
            segment: "PROFESSIONAL_LAPTOP",
            releaseDate: "January 2026",
            link: "https://www.amazon.in/s?k=HP+Spectre+x360+2026"
        },
        {
            id: 1133,
            name: "Microsoft Surface Pro 12",
            category: "Tablet",
            price: "₹1,09,990",
            priceValue: 109990,
            specs: { display: "13.2\" 120Hz OLED", cpu: "Snapdragon X Elite 2", ram: "16GB", storage: "512GB" },
            image: "assets/products/311.jpg",
            images: ["assets/products/311.jpg"],
            pros: ["Full Windows in Tablet", "New AI PC Copilot Integration", "Magnetic Flex Keyboard"],
            cons: ["Keyboard sold separately", "Battery life on legacy apps", "Expensive peripherals"],
            description: "The iconic Windows tablet gets more powerful AI features and a beautiful OLED screen.",
            antutu: 1150000,
            cameraRating: 7.5,
            segment: "PRO",
            releaseDate: "October 2025",
            link: "https://www.amazon.in/s?k=Surface+Pro+12"
        },
        {
            id: 1134,
            name: "Xiaomi Pad 8 Pro",
            category: "Tablet",
            price: "₹39,999",
            priceValue: 39999,
            specs: { display: "12.4\" 144Hz 3K LCD", cpu: "Snapdragon 8s Gen 5", ram: "12GB", storage: "256GB" },
            image: "assets/products/152.jpg",
            images: ["assets/products/152.jpg"],
            pros: ["Massive Performance Value", "Desktop-mode multitasking", "Fast 67W Charging"],
            cons: ["No OLED Option", "Software ecosystem for tabs", "Large and heavy"],
            description: "Xiaomi's pro-level tablet for 2026, targeting power users and creative professionals on a budget.",
            antutu: 1750000,
            cameraRating: 8.0,
            segment: "COMING_SOON",
            releaseDate: "July 2026",
            link: "https://www.amazon.in/s?k=Xiaomi+Pad+8+Pro"
        },
        // --- ADDING BATCH 4: EXPANDING TO 70+ HIGH-DETAIL DEVICES ---

        {
            id: 1141,
            name: "Poco M8 Pro 5G",
            category: "Phone",
            price: "₹14,999",
            priceValue: 14999,
            specs: { display: "6.79\" 90Hz LCD", cpu: "Dimensity 6300+", ram: "6GB", storage: "128GB" },
            image: "assets/products/115.jpg",
            images: ["assets/products/115.jpg"],
            pros: ["Massive Display for Media", "Glass Back Premium Feel", "Headphone Jack Included"],
            cons: ["Single Speaker", "Moderate Brightness", "Slow Charging"],
            description: "Poco's entry-level disruptor for 2026, bringing high-speed 5G to the most accessible price point.",
            antutu: 450000,
            cameraRating: 6.0,
            segment: "ALL_ROUNDER",
            releaseDate: "January 2026",
            link: "https://www.amazon.in/s?k=Poco+M8+Pro"
        },

        {
            id: 1143,
            name: "OnePlus Nord CE 5 Lite",
            category: "Phone",
            price: "₹19,999",
            priceValue: 19999,
            specs: { display: "6.67\" 120Hz AMOLED", cpu: "Snapdragon 6 Gen 4", ram: "8GB", storage: "128GB" },
            image: "assets/products/118.jpg",
            images: ["assets/products/118.jpg"],
            pros: ["OxygenOS Clean Experience", "Great Main Day Camera", "Solid Battery Backup"],
            cons: ["No Alert Slider", "Heavily plastic build", "Display bezels"],
            description: "The affordable OnePlus entry strategy for 2026, focusing on essential performance and software polish.",
            antutu: 680000,
            cameraRating: 7.0,
            segment: "ALL_ROUNDER",
            releaseDate: "April 2026",
            link: "https://www.amazon.in/s?k=Nord+CE+5+Lite"
        },

        {
            id: 1145,
            name: "Moto G56 5G",
            category: "Phone",
            price: "₹13,999",
            priceValue: 13999,
            specs: { display: "6.5\" 120Hz LCD", cpu: "Dimensity 6020", ram: "6GB", storage: "128GB" },
            image: "assets/products/n3.jpg",
            images: ["assets/products/n3.jpg"],
            pros: ["Clean Ad-Free UI", "Stereo Speakers", "Loud Output"],
            cons: ["Lower resolution screen", "Basic charging speed", "Single camera usage"],
            description: "Motorola's most affordable clean 5G experience for the masses in early 2026.",
            antutu: 420000,
            cameraRating: 5.8,
            segment: "ALL_ROUNDER",
            releaseDate: "January 2026",
            link: "https://www.amazon.in/s?k=Moto+G56"
        },

        {
            id: 1147,
            name: "Nothing Phone (2b) Plus",
            category: "Phone",
            price: "₹25,999",
            priceValue: 25999,
            specs: { display: "6.7\" 120Hz LTPO", cpu: "Dimensity 7300 Pro", ram: "8GB", storage: "256GB" },
            image: "assets/products/110.jpg",
            images: ["assets/products/110.jpg"],
            pros: ["Minimalist HUD Design", "Balanced Battery Stats", "Unique OS Experience"],
            cons: ["Limited Service Centers", "Aesthetic niche", "No HDR10+ in all apps"],
            description: "A mid-cycle refresh of the community favorite, offering better thermal pads and updated software.",
            antutu: 780000,
            cameraRating: 7.5,
            segment: "ALL_ROUNDER",
            releaseDate: "May 2025",
            link: "https://www.amazon.in/s?k=Nothing+Phone+2b"
        },
        {
            id: 1148,
            name: "Infinix Zero 50 Ultra",
            category: "Phone",
            price: "₹36,999",
            priceValue: 36999,
            specs: { display: "6.8\" 144Hz Curved", cpu: "Dimensity 9300+", ram: "12GB", storage: "512GB" },
            image: "assets/products/n2.jpg",
            images: ["assets/products/n2.jpg"],
            pros: ["Industry-leading 180W Charge", "200MP Main Camera", "Leather Back luxury"],
            cons: ["Software UI design", "Resale value concerns", "Updates consistency"],
            description: "Infinix's spec-heavy flagship, featuring 180W Thunder Charge and a massive 200MP camera sensor.",
            antutu: 1800000,
            cameraRating: 8.8,
            segment: "CAMERA",
            releaseDate: "November 2025",
            link: "https://www.amazon.in/s?k=Infinix+Zero+50"
        },
        {
            id: 1149,
            name: "ASUS Vivobook 16 2026 (COMING SOON)",
            category: "Laptop",
            price: "₹64,990",
            priceValue: 64990,
            specs: { display: "16\" FHD+ IPS", cpu: "Ryzen 7 9700U", ram: "16GB", storage: "512GB" },
            image: "assets/products/312.jpg",
            images: ["assets/products/312.jpg"],
            pros: ["Massive 16-inch Display", "NanoEdge Slim Bezels", "Full Numpad Keyboard"],
            cons: ["Build is mostly plastic", "Average Battery Life", "Heavy for students"],
            description: "A large-screen productivity machine for students and office workers, featuring the latest Ryzen efficiency.",
            gpuRating: 6.0,
            antutu: 850000,
            segment: "COMING_SOON",
            releaseDate: "April 2026",
            link: "https://www.amazon.in/s?k=Asus+Vivobook+16+2026"
        },
        {
            id: 1150,
            name: "Lenovo Yoga Slim 7i 2026 (COMING SOON)",
            category: "Laptop",
            price: "₹1,09,990",
            priceValue: 109990,
            specs: { display: "14.5\" 3K PureSight", cpu: "Core Ultra 7", ram: "16GB", storage: "1TB" },
            image: "assets/products/305.jpg",
            images: ["assets/products/305.jpg"],
            pros: ["Elegantly Crafted Build", "High-Fidelity Speakers", "Vivid OLED Clarity"],
            cons: ["Limited Ports (Dongle life)", "Webcam is basic", "Expensive MSRP"],
            description: "The premium ultrabook for creators, combining artistic design with powerful Intel Ultra silicon.",
            gpuRating: 7.2,
            antutu: 1300000,
            segment: "COMING_SOON",
            releaseDate: "May 2026",
            link: "https://www.amazon.in/s?k=Lenovo+Yoga+Slim+7i"
        },
        {
            id: 1151,
            name: "OnePlus Pad Go 2",
            category: "Tablet",
            price: "₹19,999",
            priceValue: 19999,
            specs: { display: "11.35\" 90Hz 2.4K", cpu: "Snapdragon 6 Gen 3", ram: "8GB", storage: "128GB" },
            image: "assets/products/152.jpg",
            images: ["assets/products/152.jpg"],
            pros: ["Best Display in Budget", "Premium Metal Construction", "Quad Speaker Immersion"],
            cons: ["Average Camera Quality", "Heavier than Plastic rivals", "Charging is standard"],
            description: "A media-centric tablet designed for high-definition streaming and gaming on a budget.",
            antutu: 650000,
            cameraRating: 6.0,
            segment: "ALL_ROUNDER",
            releaseDate: "November 2025",
            link: "https://www.amazon.in/s?k=OnePlus+Pad+Go+2"
        },
        {
            id: 1152,
            name: "Lava Ivory 2026 (COMING SOON)",
            category: "Tablet",
            price: "₹9,999",
            priceValue: 9999,
            specs: { display: "8\" HD Display", cpu: "Unisoc T616", ram: "4GB", storage: "64GB" },
            image: "assets/final assets/lava strom1.jpg",
            images: ["assets/final assets/lava strom1.jpg"],
            pros: ["Extremely Affordable", "Compact for Students", "SIM Slot for Calling"],
            cons: ["Low resolution panel", "Basic performance", "Plastic build"],
            description: "India's most affordable digital learning tool, tailored for primary education and basic browsing.",
            antutu: 310000,
            cameraRating: 5.0,
            segment: "COMING_SOON",
            releaseDate: "August 2026",
            link: "https://www.amazon.in/s?k=Lava+Ivory+Tablet"
        },
        // --- ADDING BATCH 5: ULTRA PREMIUM & CREATOR EXPANSION ---

        {
            id: 1181,
            name: "ASUS ROG Phone 10 Pro",
            category: "Phone",
            price: "₹99,999",
            priceValue: 99999,
            specs: { display: "6.78\" 165Hz AMOLED", cpu: "Snapdragon 8 Gen 5", ram: "24GB", storage: "1TB" },
            image: "assets/vivo-neo9-pro-10.jpg",
            images: ["assets/vivo-neo9-pro-10.jpg"],
            pros: ["Built-in Cooling Fan", "AirTrigger 8 Control", "Fastest Touch Sampling"],
            cons: ["Heavy and Industrial", "Camera is good but not elite", "Pricey Accessories"],
            description: "The absolute peak of mobile gaming, featuring 24GB of RAM and a specialized cooling architecture.",
            antutu: 2650000,
            cameraRating: 8.0,
            segment: "PERFORMANCE",
            releaseDate: "January 2026",
            link: "https://www.amazon.in/s?k=ROG+Phone+10"
        },
        {
            id: 1182,
            name: "MSI Raider GE78 2026 (COMING SOON)",
            category: "Laptop",
            price: "₹2,89,990",
            priceValue: 289990,
            specs: { display: "17\" 4K 144Hz Mini-LED", cpu: "i9-16980HK", ram: "64GB", storage: "2TB" },
            image: "assets/msi thin15 gf63.jpg",
            images: ["assets/msi thin15 gf63.jpg"],
            pros: ["World-Leading Graphics TGP", "Mystic Light RGB Bar", "Extreme Multi-tasking"],
            cons: ["Proprietary 330W Brick", "Battery life is minimal", "Very Bulky"],
            description: "A desktop replacement in a laptop form factor, designed for 4K ultra-gaming and heavy 3D workstation loads.",
            gpuRating: 10.0,
            antutu: 1950000,
            segment: "COMING_SOON",
            releaseDate: "February 2026",
            link: "https://www.amazon.in/s?k=MSI+Raider+2026"
        },
        {
            id: 1183,
            name: "Razer Blade 14 (2026) (COMING SOON)",
            category: "Laptop",
            price: "₹2,24,990",
            priceValue: 224990,
            specs: { display: "14\" QHD+ 240Hz", cpu: "Ryzen 9 9900HS", ram: "32GB", storage: "1TB" },
            image: "assets/products/314.jpg",
            images: ["assets/products/314.jpg"],
            pros: ["Unmatched Build Quality", "Most Portable Pro Power", "Chroma RGB Customization"],
            cons: ["Premium Tax (Pricing)", "Solid RAM (Non-upgradeable)", "Surface gets warm"],
            description: "The MacBook of gaming laptops, offering elite performance in a CNC-milled aluminum chassis.",
            gpuRating: 9.0,
            antutu: 1550000,
            segment: "COMING_SOON",
            releaseDate: "June 2026",
            link: "https://www.amazon.in/s?k=Razer+Blade+14"
        },
        {
            id: 1184,
            name: "ASUS Zenbook S 16 (2026)",
            category: "Laptop",
            price: "₹1,49,990",
            priceValue: 149990,
            specs: { display: "16\" 3K OLED 120Hz", cpu: "Ryzen AI 9 HX 370", ram: "32GB", storage: "1TB" },
            image: "assets/products/323.jpg",
            images: ["assets/products/323.jpg"],
            pros: ["Ceraluminum Build Texture", "Ultra-Thin 1.1cm", "AI NPU for Copilot"],
            cons: ["Limited USB-A ports", "Higher Price vs Vivobook", "No Touch by Default"],
            description: "A fusion of art and technology, utilizing high-tech ceramic-aluminum for a unique premium feel.",
            gpuRating: 7.5,
            antutu: 1400000,
            segment: "PROFESSIONAL_LAPTOP",
            releaseDate: "July 2025",
            link: "https://www.amazon.in/s?k=Zenbook+S+16"
        },
        {
            id: 1185,
            name: "Microsoft Surface Laptop 7",
            category: "Laptop",
            price: "₹1,14,990",
            priceValue: 114990,
            specs: { display: "13.8\" PixelSense Touch", cpu: "Snapdragon X Elite", ram: "16GB", storage: "512GB" },
            image: "assets/hp laptop 15.jpg",
            images: ["assets/hp laptop 15.jpg"],
            pros: ["20-Hour Battery Life", "Best-in-class Haptics", "Pure Windows Experience"],
            cons: ["Software Emulation hurdles", "Single Fan design", "Proprietary Connect charger"],
            description: "Microsoft's challenge to the MacBook Air, featuring ultra-efficient ARM processors and elite AI tools.",
            gpuRating: 6.8,
            antutu: 1250000,
            segment: "STUDENT_LAPTOP",
            releaseDate: "April 2025",
            link: "https://www.amazon.in/s?k=Surface+Laptop+7"
        },
        {
            id: 1186,
            name: "iPad Pro 13 (M5)",
            category: "Tablet",
            price: "₹1,29,900",
            priceValue: 129900,
            specs: { display: "13\" Tandem OLED", cpu: "Apple M5", ram: "16GB", storage: "256GB" },
            image: "assets/apple-m3-mxcu3hn-a-165756-v1-original-1.avif",
            images: ["assets/apple-m3-mxcu3hn-a-165756-v1-original-1.avif"],
            pros: ["World's Best Mobile Screen", "Thinnest Apple Product", "Professional Video Editing"],
            cons: ["iPadOS Software limitations", "Accessories cost ₹30k+", "No Headphone Jack"],
            description: "The most powerful tablet ever created, now with the M5 chip and the brightness of Tandem OLED technology.",
            antutu: 2500000,
            cameraRating: 9.0,
            segment: "COMING_SOON",
            releaseDate: "May 2026",
            link: "https://www.amazon.in/s?k=iPad+Pro+M5"
        },
        {
            id: 1187,
            name: "Samsung Galaxy Tab S11 Ultra",
            category: "Tablet",
            price: "₹1,19,999",
            priceValue: 119999,
            specs: { display: "14.6\" Dynamic AMOLED", cpu: "Snapdragon 8 Gen 5", ram: "16GB", storage: "512GB" },
            image: "assets/products/111.jpg",
            images: ["assets/products/111.jpg"],
            pros: ["Desktop-sized Canvas", "Free S-Pen Productivity", "Advanced Multi-Window"],
            cons: ["Too large for single hand", "Delicate build", "Battery drain at 120Hz"],
            description: "A massive productivity powerhouse that blurs the line between high-end tablet and ultra-slim laptop.",
            antutu: 2400000,
            cameraRating: 8.5,
            segment: "PRO",
            releaseDate: "January 2026",
            link: "https://www.amazon.in/s?k=Galaxy+Tab+S11+Ultra"
        },
        // --- ADDING BATCH 6: REACHING 100+ DEVICES (THE HERO EXPANSION) ---

        {
            id: 1202,
            name: "OnePlus 15 Pro",
            category: "Phone",
            price: "₹89,999",
            priceValue: 89999,
            specs: { display: "6.82\" 2K 165Hz", cpu: "Snapdragon 8 Gen 5", ram: "24GB", storage: "512GB" },
            image: "assets/products/118.jpg",
            images: ["assets/products/118.jpg"],
            pros: ["Advanced Glacial Cooling", "Hasselblad Master Edition Lenses", "150W SuperVOOC 3.0"],
            cons: ["Large Camera bump", "Brand shift to Ultra-premium", "Curation OS bloat"],
            description: "The 2026 performance beast from OnePlus, redefining the boundaries of 165Hz mobile gaming and thermal stability.",
            antutu: 2550000,
            cameraRating: 9.2,
            segment: "PERFORMANCE",
            releaseDate: "January 2026",
            link: "https://www.amazon.in/s?k=OnePlus+15"
        },
        {
            id: 1203,
            name: "Realme GT 7 Pro",
            category: "Phone",
            price: "₹54,999",
            priceValue: 54999,
            specs: { display: "6.78\" 144Hz LTPO", cpu: "Snapdragon 8 Gen 5", ram: "12GB", storage: "256GB" },
            image: "assets/products/n1.jpg",
            images: ["assets/products/n1.jpg"],
            pros: ["Cheapest 8 Gen 5 in India", "Great Haptics", "Luxury Vegan Leather"],
            cons: ["Software UI ads", "Average low light vids", "Updates speed"],
            description: "Realme's returns to the high-end flagship space with aggressive pricing and the latest Qualcomm power.",
            antutu: 2350000,
            cameraRating: 8.5,
            segment: "PERFORMANCE",
            releaseDate: "November 2025",
            link: "https://www.amazon.in/s?k=Realme+GT+7"
        },


        {
            id: 1206,
            name: "Alienware m16 R4 (2026)",
            category: "Laptop",
            price: "₹2,14,990",
            priceValue: 214990,
            specs: { display: "16\" 2.5K 480Hz", cpu: "i9-16900HX", ram: "32GB", storage: "1TB" },
            image: "assets/msi thin15 gf63.jpg",
            images: ["assets/msi thin15 gf63.jpg"],
            pros: ["Extreme Refresh Rate 480Hz", "Legend-3 Industrial Design", "Cryo-Tech Cooling"],
            cons: ["Very Heavy", "Short Battery Life", "Expensive Warranty"],
            description: "Designed for the ultimate competitive gamer who needs the highest refresh rate panel on a laptop.",
            gpuRating: 9.8,
            antutu: 1750000,
            segment: "COMING_SOON",
            releaseDate: "March 2026",
            link: "https://www.amazon.in/s?k=Alienware+m16"
        },
        {
            id: 1207,
            name: "Acer Swift Edge 16 (2026)",
            category: "Laptop",
            price: "₹94,990",
            priceValue: 94990,
            specs: { display: "16\" 4K OLED", cpu: "Ryzen 7 9800U", ram: "16GB", storage: "512GB" },
            image: "assets/products/312.jpg",
            images: ["assets/products/312.jpg"],
            pros: ["World's Lightest 16-inch", "OLED Color Depth", "Elegant Magnesium Build"],
            cons: ["Flex in keyboard", "Small battery to keep weight low", "Basic WebCam"],
            description: "The perfect laptop for students and travelers who need a large, high-res screen without the weight.",
            gpuRating: 6.2,
            antutu: 950000,
            segment: "COMING_SOON",
            releaseDate: "May 2026",
            link: "https://www.amazon.in/s?k=Acer+Swift+Edge"
        },
        {
            id: 1208,
            name: "OnePlus Pad 3",
            category: "Tablet",
            price: "₹42,999",
            priceValue: 42999,
            specs: { display: "12.1\" 144Hz IPS 3K", cpu: "Snapdragon 8 Gen 4", ram: "12GB", storage: "256GB" },
            image: "assets/products/152.jpg",
            images: ["assets/products/152.jpg"],
            pros: ["Flagship Phone Speed", "Great 7:5 Aspect Ratio", "Affordable Stylus Ecosystem"],
            cons: ["No OLED Option", "Large for reading", "Average primary camera"],
            description: "A high-performance tablet that brings the speed of 2025 flagships to a productive large screen.",
            antutu: 1950000,
            cameraRating: 7.2,
            segment: "PERFORMANCE",
            releaseDate: "June 2025",
            link: "https://www.amazon.in/s?k=OnePlus+Pad+3"
        },
        {
            id: 1209,
            name: "Redmi Pad Pro 2",
            category: "Tablet",
            price: "₹24,999",
            priceValue: 24999,
            specs: { display: "12.1\" 120Hz LCD", cpu: "Snapdragon 7s Gen 3", ram: "8GB", storage: "128GB" },
            image: "assets/products/111.jpg",
            images: ["assets/products/111.jpg"],
            pros: ["Stunning Media Display", "Reliable Performance", "Great Battery Backup"],
            cons: ["Plastic build feel", "Slow charging", "Average brightness"],
            description: "The king of budget media tablets, offering a massive 12.1 inch screen for students and video lovers.",
            antutu: 750000,
            cameraRating: 6.5,
            segment: "STUDENT_LAPTOP",
            releaseDate: "September 2025",
            link: "https://www.amazon.in/s?k=Redmi+Pad+Pro"
        },
        // --- ADDING BATCH 7: THE FINAL CENTURY (100+ DEVICES) ---




        {
            id: 1224,
            name: "iQOO Neo 11",
            category: "Phone",
            price: "₹34,999",
            priceValue: 34999,
            specs: { display: "6.78\" 144Hz AMOLED", cpu: "Snapdragon 8 Gen 4", ram: "12GB", storage: "256GB" },
            image: "assets/vivo-neo9-pro-10.jpg",
            images: ["assets/vivo-neo9-pro-10.jpg"],
            pros: ["Flagship Processor at 35k", "Vapor Chamber Cooling", "Gaming display chip"],
            cons: ["Plastic Frame", "Funtouch OS", "Average Cameras"],
            description: "The raw performance champion of the mid-range segment for late 2025/2026.",
            antutu: 1950000,
            cameraRating: 7.0,
            segment: "PERFORMANCE",
            releaseDate: "December 2025",
            link: "https://www.amazon.in/s?k=iQOO+Neo+11"
        },
        {
            id: 1225,
            name: "Poco F7 5G",
            category: "Phone",
            price: "₹26,999",
            priceValue: 26999,
            specs: { display: "6.67\" 1.5K 120Hz", cpu: "Snapdragon 8s Gen 4", ram: "8GB", storage: "256GB" },
            image: "assets/products/115.jpg",
            images: ["assets/products/115.jpg"],
            pros: ["Insane Value for Money", "Sharp Display", "High Touch Sampling"],
            cons: ["Plastic build", "System Ads", "Camera lacks OIS clarity"],
            description: "The 2025/2026 successor to the most popular performance mid-ranger in India.",
            antutu: 1650000,
            cameraRating: 7.0,
            segment: "PERFORMANCE",
            releaseDate: "May 2025",
            link: "https://www.amazon.in/s?k=Poco+F7"
        },


        {
            id: 1228,
            name: "HP Pavilion 15 (2026)",
            category: "Laptop",
            price: "₹54,990",
            priceValue: 54990,
            specs: { display: "15.6\" FHD IPS", cpu: "Ryzen 5 9600U", ram: "16GB", storage: "512GB" },
            image: "assets/hp laptop 15.jpg",
            images: ["assets/hp laptop 15.jpg"],
            pros: ["Solid Everyday Performance", "Backlit Keyboard", "Great value"],
            cons: ["Plastic Build", "Display average brightness", "Battery life is just 6 hours"],
            description: "The standard student and office choice, now updated with 2026 Ryzen architecture.",
            gpuRating: 5.5,
            antutu: 750000,
            segment: "COMING_SOON",
            releaseDate: "April 2026",
            link: "https://www.amazon.in/s?k=HP+Pavilion+2026"
        },
        {
            id: 1229,
            name: "Dell Inspiron 14 Plus (2026)",
            category: "Laptop",
            price: "₹89,990",
            priceValue: 89990,
            specs: { display: "14\" 2.2K Display", cpu: "Core Ultra 5 Gen 2", ram: "16GB", storage: "1TB" },
            image: "assets/msi thin15 gf63.jpg",
            images: ["assets/msi thin15 gf63.jpg"],
            pros: ["Robust Aluminum Build", "Great keyboard", "AI PC features"],
            cons: ["Screen is not OLED", "Quiet Speakers", "Limited Colors"],
            description: "A reliable premium workhorse for young professionals and university students.",
            gpuRating: 6.5,
            antutu: 1100000,
            segment: "COMING_SOON",
            releaseDate: "May 2026",
            link: "https://www.amazon.in/s?k=Dell+Inspiron+14+Plus"
        },
        {
            id: 1230,
            name: "MacBook Air M4 (13\")",
            category: "Laptop",
            price: "₹1,09,900",
            priceValue: 109900,
            specs: { display: "13.6\" Liquid Retina", cpu: "Apple M4", ram: "16GB", storage: "256GB" },
            image: "assets/apple-m3-mxcu3hn-a-165756-v1-original-1.avif",
            images: ["assets/apple-m3-mxcu3hn-a-165756-v1-original-1.avif"],
            pros: ["World's Best Battery Life", "Fanless Silence", "Elite Trackpad"],
            cons: ["Limited Ports", "Storage upgrade is very pricey", "Bezel notch"],
            description: "The refined 13-inch Air with the M4 chip, perfect for mobile students and office tasks.",
            gpuRating: 7.2,
            antutu: 1450000,
            segment: "STUDENT_LAPTOP",
            releaseDate: "March 2025",
            link: "https://www.amazon.in/s?k=MacBook+Air+M4"
        },
        {
            id: 1231,
            name: "Lenovo Legion 5 (2026)",
            category: "Laptop",
            price: "₹1,14,990",
            priceValue: 114990,
            specs: { display: "15.6\" 165Hz QHD", cpu: "Ryzen 7 9800H", ram: "16GB", storage: "512GB" },
            image: "assets/products/323.jpg",
            images: ["assets/products/323.jpg"],
            pros: ["Excellent Cooling", "Privacy Shutter Cam", "Best gaming keyboard"],
            cons: ["Heavy Brick", "Plain Design", "Battery is average"],
            description: "The gaming standard for budget enthusiasts, offering rock-solid stability and high frame rates.",
            gpuRating: 8.2,
            antutu: 1200000,
            segment: "COMING_SOON",
            releaseDate: "June 2026",
            link: "https://www.amazon.in/s?k=Lenovo+Legion+5"
        },
        {
            id: 1232,
            name: "Samsung Galaxy Tab A11",
            category: "Tablet",
            price: "₹14,999",
            priceValue: 14999,
            specs: { display: "10.1\" HD LCD", cpu: "Exynos 1330", ram: "4GB", storage: "64GB" },
            image: "assets/products/111.jpg",
            images: ["assets/products/111.jpg"],
            pros: ["Most Affordable Samsung Tablet", "Great for Kids", "Build reliability"],
            cons: ["HD only screen", "Plastic build", "Slow charging"],
            description: "The perfect entry-level tablet for media consumption and school work during 2026.",
            antutu: 380000,
            cameraRating: 5.5,
            segment: "COMING_SOON",
            releaseDate: "August 2026",
            link: "https://www.amazon.in/s?k=Galaxy+Tab+A"
        },
        {
            id: 1233,
            name: "Realme Pad 3",
            category: "Tablet",
            price: "₹18,999",
            priceValue: 18999,
            specs: { display: "11\" 90Hz LCD", cpu: "Helio G99 Ultimate", ram: "6GB", storage: "128GB" },
            image: "assets/products/152.jpg",
            images: ["assets/products/152.jpg"],
            pros: ["Quad Speakers", "Metal Slim Design", "Fluid 90Hz"],
            cons: ["Average Battery", "Basic Software", "Camera quality"],
            description: "A lifestyle tablet focusing on slim design and great audio-visual experience for students.",
            antutu: 420000,
            cameraRating: 6.0,
            segment: "ALL_ROUNDER",
            releaseDate: "November 2025",
            link: "https://www.amazon.in/s?k=Realme+Pad+3"
        },
        {
            id: 1234,
            name: "Redmi Note 15 Pro",
            category: "Phone",
            price: "₹28,999",
            priceValue: 28999,
            specs: { display: "6.67\" 1.5K 120Hz", cpu: "Dimensity 8300", ram: "8GB", storage: "256GB" },
            image: "assets/products/n1.jpg",
            images: ["assets/products/n1.jpg"],
            pros: ["Great Display for price", "Balanced performance", "Fast Charging 67W"],
            cons: ["HyperOS Bloat", "Mainly plastic", "Average secondary cams"],
            description: "Xiaomi's best value mid-range phone for early 2026, balancing all core tech needs.",
            antutu: 1350000,
            cameraRating: 8.0,
            segment: "ALL_ROUNDER",
            releaseDate: "January 2026",
            link: "https://www.amazon.in/s?k=Redmi+Note+15"
        },

        {
            id: 1236,
            name: "Nothing Phone (3) Lite",
            category: "Phone",
            price: "₹34,999",
            priceValue: 34999,
            specs: { display: "6.5\" 120Hz OLED", cpu: "Snapdragon 7s Gen 5", ram: "8GB", storage: "256GB" },
            image: "assets/products/110.jpg",
            images: ["assets/products/110.jpg"],
            pros: ["Compact Nothing Design", "Clean Software", "Premium build"],
            cons: ["No charger", "Glyph is simplified", "Niche design"],
            description: "A compact version of the Phone (3) for those who want the style but at a lower cost.",
            antutu: 720000,
            cameraRating: 7.5,
            segment: "ALL_ROUNDER",
            releaseDate: "August 2025",
            link: "https://www.amazon.in/s?k=Nothing+Phone+Lite"
        },
        {
            id: 1237,
            name: "HP Envy x360 14 (2026)",
            category: "Laptop",
            price: "₹79,990",
            priceValue: 79990,
            specs: { display: "14\" 2 in 1 Touch", cpu: "Ryzen 7 9800U", ram: "16GB", storage: "512GB" },
            image: "assets/hp laptop 15.jpg",
            images: ["assets/hp laptop 15.jpg"],
            pros: ["Versatile hinge", "Solid metal build", "Great for creatives"],
            cons: ["Pricey vs standard", "Stylus extra", "Display is IPS"],
            description: "A versatile 2-in-1 laptop for students and designers who need touch input flexibility.",
            gpuRating: 6.0,
            antutu: 950000,
            segment: "COMING_SOON",
            releaseDate: "June 2026",
            link: "https://www.amazon.in/s?k=HP+Envy+x360+2026"
        },


        {
            id: 1240,
            name: "Poco M8 Pro",
            category: "Phone",
            price: "₹12,999",
            priceValue: 12999,
            specs: { display: "6.79\" 90Hz LCD", cpu: "Dimensity 6020", ram: "6GB", storage: "128GB" },
            image: "assets/products/115.jpg",
            images: ["assets/products/115.jpg"],
            pros: ["Large Media Display", "Trusted Poco Performance", "Cheap"],
            cons: ["Dated notch", "Slow charging", "Plastic"],
            description: "The affordable media king from Poco, focusing on screen size and battery life.",
            antutu: 350000,
            cameraRating: 5.8,
            segment: "ALL_ROUNDER",
            releaseDate: "January 2026",
            link: "https://www.amazon.in/s?k=Poco+M8"
        }
    ],
    news: [
        {
            id: 1,
            title: "Tandem OLED: The Next Frontier in Laptop Displays",
            category: "HARDWARE",
            date: "JAN 03, 2026",
            excerpt: "How Dell and Apple are leading the charge in double-layered display technology for 2026.",
            image: "assets/products/501.jpg",
            url: "#"
        },
        {
            id: 2,
            title: "Qualcomm Snapdragon 8 Gen 5 Shatters Benchmarks",
            category: "MOBILE",
            date: "JAN 02, 2026",
            excerpt: "The first 2nm mobile chipset reveals a 40% performance jump in early tests.",
            image: "assets/products/n2.jpg",
            url: "#"
        },
        {
            id: 3,
            title: "The Return of the Metal Unibody",
            category: "HARDWARE",
            date: "JAN 01, 2026",
            excerpt: "OnePlus and Nothing are reviving the iconic aluminum build in their mid-range lineup.",
            image: "assets/products/118.jpg",
            url: "#"
        }
    ]
};
